server:
  port: 9001
spring:
  application:
    name: cloud-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    #自定义服务ID名称
    instance-id: cloud-provider-9001
    #显示IP地址
    prefer-ip-address: true
#日志
logging:
  level:
    com:
      cto:
        cloud: debug
    org:
      springframework:
        web: info
  file: log/cloud-provider.log

